package hibernate;
// Generated May 7, 2020 2:41:39 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private int id;
     private String FName;
     private String LName;
     private String mobile;
     private String email;
     private Date dob;
     private String picPath;
     private String username;
     private String password;
     private Set loginHistories = new HashSet(0);

    public Admin() {
    }

	
    public Admin(int id) {
        this.id = id;
    }
    public Admin(int id, String FName, String LName, String mobile, String email, Date dob, String picPath, String username, String password, Set loginHistories) {
       this.id = id;
       this.FName = FName;
       this.LName = LName;
       this.mobile = mobile;
       this.email = email;
       this.dob = dob;
       this.picPath = picPath;
       this.username = username;
       this.password = password;
       this.loginHistories = loginHistories;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public String getLName() {
        return this.LName;
    }
    
    public void setLName(String LName) {
        this.LName = LName;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getPicPath() {
        return this.picPath;
    }
    
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getLoginHistories() {
        return this.loginHistories;
    }
    
    public void setLoginHistories(Set loginHistories) {
        this.loginHistories = loginHistories;
    }




}


