package hibernate;
// Generated May 7, 2020 2:41:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Product product;
     private Date datetime;
     private Integer qty;

    public Cart() {
    }

	
    public Cart(Customer customer, Product product) {
        this.customer = customer;
        this.product = product;
    }
    public Cart(Customer customer, Product product, Date datetime, Integer qty) {
       this.customer = customer;
       this.product = product;
       this.datetime = datetime;
       this.qty = qty;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


