package hibernate;
// Generated May 7, 2020 2:41:39 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer id;
     private DStatus DStatus;
     private Double fee;
     private String address;
     private Date date;
     private Set invoiceItems = new HashSet(0);

    public Delivery() {
    }

	
    public Delivery(DStatus DStatus) {
        this.DStatus = DStatus;
    }
    public Delivery(DStatus DStatus, Double fee, String address, Date date, Set invoiceItems) {
       this.DStatus = DStatus;
       this.fee = fee;
       this.address = address;
       this.date = date;
       this.invoiceItems = invoiceItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DStatus getDStatus() {
        return this.DStatus;
    }
    
    public void setDStatus(DStatus DStatus) {
        this.DStatus = DStatus;
    }
    public Double getFee() {
        return this.fee;
    }
    
    public void setFee(Double fee) {
        this.fee = fee;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set invoiceItems) {
        this.invoiceItems = invoiceItems;
    }




}


