package hibernate;
// Generated May 7, 2020 2:41:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DStatus generated by hbm2java
 */
public class DStatus  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set deliveries = new HashSet(0);

    public DStatus() {
    }

    public DStatus(String name, Set deliveries) {
       this.name = name;
       this.deliveries = deliveries;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDeliveries() {
        return this.deliveries;
    }
    
    public void setDeliveries(Set deliveries) {
        this.deliveries = deliveries;
    }




}


