package hibernate;
// Generated May 7, 2020 2:41:39 PM by Hibernate Tools 4.3.1



/**
 * LatestProducts generated by hbm2java
 */
public class LatestProducts  implements java.io.Serializable {


     private Integer id;
     private Product product;

    public LatestProducts() {
    }

    public LatestProducts(Product product) {
       this.product = product;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


