package hibernate;
// Generated May 7, 2020 2:41:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LogStatus generated by hbm2java
 */
public class LogStatus  implements java.io.Serializable {


     private int id;
     private String name;
     private Set loginHistories = new HashSet(0);

    public LogStatus() {
    }

	
    public LogStatus(int id) {
        this.id = id;
    }
    public LogStatus(int id, String name, Set loginHistories) {
       this.id = id;
       this.name = name;
       this.loginHistories = loginHistories;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getLoginHistories() {
        return this.loginHistories;
    }
    
    public void setLoginHistories(Set loginHistories) {
        this.loginHistories = loginHistories;
    }




}


