package hibernate;
// Generated May 7, 2020 2:41:39 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer PId;
     private Discount discount;
     private Material material;
     private Neck neck;
     private Occasion occasion;
     private PrintPattern printPattern;
     private ReturnType returnType;
     private Sleeve sleeve;
     private SpOffers spOffers;
     private String PName;
     private Integer qty;
     private Date date;
     private String picPath;
     private Integer status;
     private Double price;
     private Double cost;
     private String sizes;
     private String color;
     private Integer rating;
     private Set carts = new HashSet(0);
     private Set wishLists = new HashSet(0);
     private Set invoiceItems = new HashSet(0);
     private Set latestProductses = new HashSet(0);

    public Product() {
    }

	
    public Product(Discount discount, Material material, Neck neck, Occasion occasion, PrintPattern printPattern, ReturnType returnType, Sleeve sleeve, SpOffers spOffers) {
        this.discount = discount;
        this.material = material;
        this.neck = neck;
        this.occasion = occasion;
        this.printPattern = printPattern;
        this.returnType = returnType;
        this.sleeve = sleeve;
        this.spOffers = spOffers;
    }
    public Product(Discount discount, Material material, Neck neck, Occasion occasion, PrintPattern printPattern, ReturnType returnType, Sleeve sleeve, SpOffers spOffers, String PName, Integer qty, Date date, String picPath, Integer status, Double price, Double cost, String sizes, String color, Integer rating, Set carts, Set wishLists, Set invoiceItems, Set latestProductses) {
       this.discount = discount;
       this.material = material;
       this.neck = neck;
       this.occasion = occasion;
       this.printPattern = printPattern;
       this.returnType = returnType;
       this.sleeve = sleeve;
       this.spOffers = spOffers;
       this.PName = PName;
       this.qty = qty;
       this.date = date;
       this.picPath = picPath;
       this.status = status;
       this.price = price;
       this.cost = cost;
       this.sizes = sizes;
       this.color = color;
       this.rating = rating;
       this.carts = carts;
       this.wishLists = wishLists;
       this.invoiceItems = invoiceItems;
       this.latestProductses = latestProductses;
    }
   
    public Integer getPId() {
        return this.PId;
    }
    
    public void setPId(Integer PId) {
        this.PId = PId;
    }
    public Discount getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Discount discount) {
        this.discount = discount;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public Neck getNeck() {
        return this.neck;
    }
    
    public void setNeck(Neck neck) {
        this.neck = neck;
    }
    public Occasion getOccasion() {
        return this.occasion;
    }
    
    public void setOccasion(Occasion occasion) {
        this.occasion = occasion;
    }
    public PrintPattern getPrintPattern() {
        return this.printPattern;
    }
    
    public void setPrintPattern(PrintPattern printPattern) {
        this.printPattern = printPattern;
    }
    public ReturnType getReturnType() {
        return this.returnType;
    }
    
    public void setReturnType(ReturnType returnType) {
        this.returnType = returnType;
    }
    public Sleeve getSleeve() {
        return this.sleeve;
    }
    
    public void setSleeve(Sleeve sleeve) {
        this.sleeve = sleeve;
    }
    public SpOffers getSpOffers() {
        return this.spOffers;
    }
    
    public void setSpOffers(SpOffers spOffers) {
        this.spOffers = spOffers;
    }
    public String getPName() {
        return this.PName;
    }
    
    public void setPName(String PName) {
        this.PName = PName;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getPicPath() {
        return this.picPath;
    }
    
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public String getSizes() {
        return this.sizes;
    }
    
    public void setSizes(String sizes) {
        this.sizes = sizes;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set wishLists) {
        this.wishLists = wishLists;
    }
    public Set getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set invoiceItems) {
        this.invoiceItems = invoiceItems;
    }
    public Set getLatestProductses() {
        return this.latestProductses;
    }
    
    public void setLatestProductses(Set latestProductses) {
        this.latestProductses = latestProductses;
    }




}


