package hibernate;
// Generated May 7, 2020 2:41:39 PM by Hibernate Tools 4.3.1



/**
 * Sizes generated by hbm2java
 */
public class Sizes  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Sizes() {
    }

    public Sizes(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


