package hibernate;
// Generated May 7, 2020 2:41:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SpOffers generated by hbm2java
 */
public class SpOffers  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer butCount;
     private Integer getCount;
     transient private Set products = new HashSet(0);

    public SpOffers() {
    }

    public SpOffers(String name, Integer butCount, Integer getCount, Set products) {
       this.name = name;
       this.butCount = butCount;
       this.getCount = getCount;
       this.products = products;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getButCount() {
        return this.butCount;
    }
    
    public void setButCount(Integer butCount) {
        this.butCount = butCount;
    }
    public Integer getGetCount() {
        return this.getCount;
    }
    
    public void setGetCount(Integer getCount) {
        this.getCount = getCount;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


